theme: jekyll-theme-slate
title: 学而思
author: winjeg
aubout: "一个地地道道的工程师，擅长Mysql, linux, Java, golang"
indexContent: true
style: index.css
blogName: "winjeg"
favicon: 'favicon.ico'
copyright: '21th@winjeg 转载请附上源地址'

