theme: jekyll-theme-architect
title: 学而思, 行而知
author: winjeg
aubout: "一个地地道道的工程师，擅长Mysql, linux, Java, golang"
indexContent: true
style: index.css
favicon: 'favicon.ico'
copyright: '21th@winjeg 转载请附上源地址'

